(() => {
  const client = window.supabaseClient; const $ = id => document.getElementById(id); let users = []; let timer;
  const escapeHtml = value => String(value || "").replace(/[&<>'"]/g, char => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "'":"&#39;", '"':"&quot;" }[char]));
  const formatDate = value => value ? new Intl.DateTimeFormat("fr-CA", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
  const toast = text => { clearTimeout(timer); $("toast").textContent = `✓ ${text}`; $("toast").classList.remove("hidden"); timer = setTimeout(() => $("toast").classList.add("hidden"), 2500); };
  const showError = (text = "") => { $("adminError").textContent = text; $("adminError").classList.toggle("hidden", !text); };
  async function callAdmin(body) { const { data, error } = await client.functions.invoke("admin-users", { body }); if (error) throw error; if (data?.error) throw new Error(data.error); return data; }
  function render() { const rows = $("userRows"); rows.replaceChildren(); users.forEach(user => { const tr = document.createElement("tr"); tr.innerHTML = `<td><strong>${escapeHtml(user.full_name || "—")}</strong></td><td>${escapeHtml(user.email)}</td><td>${formatDate(user.created_at)}</td><td>${formatDate(user.last_sign_in_at)}</td><td><button class="edit" data-reset="${user.email}" type="button">Réinitialiser le mot de passe</button> <button class="danger" data-delete="${user.id}" type="button">Supprimer</button></td>`; rows.append(tr); }); $("emptyState").classList.toggle("hidden", users.length !== 0); rows.querySelectorAll("[data-reset]").forEach(button => button.addEventListener("click", () => resetPassword(button.dataset.reset))); rows.querySelectorAll("[data-delete]").forEach(button => button.addEventListener("click", () => deleteUser(button.dataset.delete))); }
  async function loadUsers() { showError(); $("refreshButton").disabled = true; try { const data = await callAdmin({ action: "list" }); users = data.users || []; render(); } catch (error) { showError(error.message || "Accès administrateur refusé."); } finally { $("refreshButton").disabled = false; } }
  async function resetPassword(email) { if (!confirm(`Envoyer un lien de réinitialisation à ${email}?`)) return; try { await callAdmin({ action: "reset_password", email }); toast("Lien de réinitialisation envoyé."); } catch (error) { showError(error.message); } }
  async function deleteUser(userId) { const user = users.find(item => item.id === userId); if (!user || !confirm(`Supprimer définitivement le compte de ${user.email}?`)) return; try { await callAdmin({ action: "delete", user_id: userId }); users = users.filter(item => item.id !== userId); render(); toast("Compte supprimé."); } catch (error) { showError(error.message); } }
  async function createTestUser() { if (!confirm("Créer un compte coach de test? Tu pourras le supprimer ensuite ici.")) return; try { const data = await callAdmin({ action: "create_test" }); await loadUsers(); alert(`Compte test créé.\n\nCourriel : ${data.email}\nMot de passe : ${data.password}\n\nGarde ces identifiants maintenant : le mot de passe ne sera plus affiché.`); } catch (error) { showError(error.message); } }
  $("refreshButton").addEventListener("click", loadUsers); $("createTestButton").addEventListener("click", createTestUser); $("logoutButton").addEventListener("click", async () => { await client.auth.signOut(); window.location.href = "../login.html"; }); client.auth.getSession().then(({ data }) => { if (!data.session) window.location.href = "../login.html"; else loadUsers(); });
})();
