(() => {
  const client = window.supabaseClient; const $ = id => document.getElementById(id); const dashboard = window.APP_DASHBOARD_PATH || "./"; let signup = false;
  const message = (text, type = "error") => { const el = $(type === "error" ? "authError" : "authSuccess"); el.textContent = text; el.classList.remove("hidden"); };
  const clearMessages = () => { $("authError").classList.add("hidden"); $("authSuccess").classList.add("hidden"); };
  const friendlyError = error => error.message.includes("Invalid login credentials") ? "Courriel ou mot de passe incorrect." : error.message.includes("User already registered") ? "Ce courriel est déjà utilisé." : error.message;
  function setMode(next) { signup = next; clearMessages(); document.querySelectorAll(".signup-only").forEach(el => el.classList.toggle("hidden", !signup)); $("authTitle").textContent = signup ? "Créer un compte" : "Connexion"; $("authIntro").textContent = signup ? "Crée ton espace coach et ton gym." : "Accède à la liste de tes athlètes."; $("authSubmit").textContent = signup ? "Créer mon compte" : "Se connecter"; $("authToggle").textContent = signup ? "J’ai déjà un compte" : "Créer un compte coach"; }
  client.auth.getSession().then(({ data }) => { if (data.session) window.location.href = dashboard; });
  $("authToggle").addEventListener("click", () => setMode(!signup));
  $("authForm").addEventListener("submit", async event => { event.preventDefault(); clearMessages(); $("authSubmit").disabled = true; try { const email = $("email").value.trim(); const password = $("password").value; if (signup) { const { data, error } = await client.auth.signUp({ email, password, options: { data: { full_name: $("fullName").value.trim(), gym_name: $("gymName").value.trim(), gym_address: $("gymAddress").value.trim() } } }); if (error) throw error; message(data.session ? "Compte créé. Tu peux maintenant accéder à ton tableau de bord." : "Compte créé. Vérifie ton courriel, puis connecte-toi.", "success"); } else { const { error } = await client.auth.signInWithPassword({ email, password }); if (error) throw error; window.location.href = dashboard; } } catch (error) { message(friendlyError(error)); } finally { $("authSubmit").disabled = false; } });
})();
