import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,readdir} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('journal history and library folders enforce direct sharing and ownership in PostgreSQL',async()=>{
 const db=new PGlite();
 const athlete='11000000-0000-4000-8000-000000000001',coach='11000000-0000-4000-8000-000000000002',other='11000000-0000-4000-8000-000000000003';
 const scalar=async(sql,args=[])=>Object.values((await db.query(sql,args)).rows[0]||{})[0];
 const admin=()=>db.exec('reset role');
 const login=async id=>{await admin();await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');};
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.role() returns text language sql stable as $$select 'authenticated'::text$$;grant usage on schema public,auth to anon,authenticated,service_role;grant execute on function auth.uid(),auth.role() to anon,authenticated,service_role;alter default privileges in schema public grant all on tables to public,anon,authenticated,service_role;`);
 const dir=new URL('../supabase/migrations/',import.meta.url);for(const name of (await readdir(dir)).filter(f=>f.endsWith('.sql')).sort())await db.exec(await readFile(new URL(name,dir),'utf8'));
 for(const [id,role] of [[athlete,'athlete'],[coach,'coach'],[other,'coach']])await db.query('insert into auth.users(id,email,raw_user_meta_data) values($1,$2,$3)',[id,id+'@example.test',JSON.stringify({full_name:role,account_type:role,birth_date:'2000-01-01'})]);
 const athleteId=await scalar('select id from public.athletes where user_id=$1',[athlete]);
 await db.query("insert into public.coach_athletes(athlete_id,coach_id,status,can_view_calendar,can_add_sessions) values($1,$2,'accepted',true,false)",[athleteId,coach]);
 await login(athlete);
 const entry=await scalar("insert into public.journal_entries(athlete_id,title,body) values($1,'Garde','Mon observation') returning id",[athleteId]);
 assert.equal(await scalar('select count(*) from public.journal_updates where entry_id=$1',[entry]),1);
 await admin();assert.equal(await scalar('select onboarding_stub from public.athletes where id=$1',[athleteId]),false);
 await login(other);assert.equal(await scalar('select count(*) from public.journal_entries'),0);assert.equal(await scalar('select count(*) from public.journal_updates'),0);
 await assert.rejects(()=>db.query("insert into public.journal_entries(athlete_id,title) values($1,'Intrusion')",[athleteId]));
 await login(coach);assert.equal(await scalar('select count(*) from public.journal_entries'),1);
 assert.equal((await db.query("update public.journal_entries set status='work' where id=$1 returning id",[entry])).rows.length,0);
 await assert.rejects(()=>db.query("insert into public.journal_updates(entry_id,content) values($1,'Conseil')",[entry]));
 await admin();await db.query('update public.coach_athletes set can_add_sessions=true where athlete_id=$1',[athleteId]);
 await login(coach);
 await assert.rejects(()=>db.query("update public.journal_entries set body='Remplacement' where id=$1",[entry]),/auteur/);
 await db.query("update public.journal_entries set status='work' where id=$1",[entry]);
 await db.query("insert into public.journal_updates(entry_id,content) values($1,'Conseil du coach')",[entry]);
 assert.equal(await scalar("select count(*) from public.journal_updates where kind='status' and content='work'"),1);
 await assert.rejects(()=>db.query("insert into public.journal_updates(entry_id,kind,content) values($1,'status','maintain')",[entry]),/permission denied/);
 await assert.rejects(()=>db.query('update public.journal_entries set created_by=$1 where id=$2',[coach,entry]),/permission denied/);
 await login(athlete);assert.equal(await scalar('select count(*) from public.journal_updates'),3);
 const previous=await scalar('select updated_at::text from public.journal_entries where id=$1',[entry]);
 await db.query('update public.journal_entries set archived=true where id=$1',[entry]);
 await assert.rejects(()=>db.query("insert into public.journal_updates(entry_id,content) values($1,'Tardif')",[entry]));
 assert.equal((await db.query("update public.journal_entries set status='maintain' where id=$1 and updated_at=$2 returning id",[entry,previous])).rows.length,0);
 await db.query('update public.journal_entries set archived=false where id=$1',[entry]);
 await admin();await db.query("update public.coach_athletes set status='revoked' where athlete_id=$1",[athleteId]);
 await login(coach);assert.equal(await scalar('select count(*) from public.journal_entries'),0);assert.equal(await scalar('select count(*) from public.journal_updates'),0);
 await assert.rejects(()=>db.query("insert into public.journal_updates(entry_id,content) values($1,'Après révocation')",[entry]));
 const folder=await scalar("insert into public.library_folders(name) values('Mes séances') returning id");
 const template=await scalar("insert into public.session_templates(coach_id,title,sport,blocks,kind,folder_id) values($1,'Jog','running','[]','session',$2) returning id",[coach,folder]);
 await login(other);assert.equal(await scalar('select count(*) from public.library_folders'),0);
 await assert.rejects(()=>db.query("insert into public.session_templates(coach_id,title,sport,blocks,kind,folder_id) values($1,'Intrusion','running','[]','session',$2)",[other,folder]),/foreign key/);
 await assert.rejects(()=>db.query("insert into public.library_folders(owner_id,name) values($1,'Usurpation')",[coach]),/permission denied/);
 await login(coach);await db.query('delete from public.library_folders where id=$1',[folder]);assert.equal(await scalar('select folder_id from public.session_templates where id=$1',[template]),null);assert.equal(await scalar('select title from public.session_templates where id=$1',[template]),'Jog');
 await admin();await db.exec('set role anon');await assert.rejects(()=>db.query('select * from public.journal_entries'),/permission denied/);await assert.rejects(()=>db.query('select * from public.library_folders'),/permission denied/);
 }finally{await db.close();}
});
